- hosts: vmhost
  strategy: free
  connection: local
  roles:
    - role: vm-rollback

- hosts: vm_guests
  roles:
    - role: build-env
    - role: "{{var_rebuild_role}}"

# - hosts: vm_guests
#   roles:
#     - role: update-repo
