- name: Install rpm build
  become: true
  package:
    name:
      - rpm-build
      - createrepo
    state: present
  when: ansible_os_family in var_redhat_based_os

- name: Install deb build
  become: true
  package:
    name:
      - build-essential
      - reprepro
    state: present
  when: ansible_os_family in var_debian_based_os
